;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        dabbrev-expand
        kill-sexp
        mc/mark-next-lines
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-wrap-round
        ))

(setq mc/cmds-to-run-once
      '(
        lsp-ui-doc--handle-mouse-movement
        persp-switch-to-buffer*
        ))
