;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mark-sexp
        mc/mark-next-lines
        puni-forward-delete-char
        puni-forward-kill-word
        puni-wrap-curly
        undo-only
        ))

(setq mc/cmds-to-run-once
      '(
        puni-backward-delete-char
        ))
