;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        combobulate-envelop-tsx-ts-mode-wrap-parentheses
        combobulate-navigate-up
        corfu-complete
        corfu-complete-and-quit
        corfu-next
        corfu-quit
        down-list
        end-of-buffer
        end-of-visual-line
        ignore-preserving-kill-region
        indent-for-tab-command
        kill-sexp
        kmacro-end-or-call-macro
        lsp-ui-doc--handle-mouse-movement
        mark-sexp
        mc/mark-all-in-region-regexp
        mc/mark-next-lines
        org-end-of-line
        org-self-insert-command
        puni-backward-delete-char
        puni-backward-kill-word
        puni-backward-sexp-or-up-list
        puni-forward-delete-char
        puni-forward-kill-word
        puni-forward-sexp-or-up-list
        puni-kill-line
        puni-raise
        puni-splice
        puni-wrap-curly
        puni-wrap-round
        region-bindings-doublequote
        undo-only
        whole-line-or-region-kill-ring-save
        ))

(setq mc/cmds-to-run-once
      '(
        helpful-key
        pixel-scroll-precision
        ))
